### ISSUE TITLE
Node.js Paketo Language Family Buildpacks should receive implementation buildpack updates

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/nodejs#1]
**Context**
We should set up our pipelines to start updating the language family CNB level buildpack.toml anytime there is a new version of one of its Implementation Paketo Buildpacks.

**Proposal**
Attempt to use Github Actions to start auto-PRing implementation CNB versions in the Paketo Node.js Language family buildpacks. If pipelines pass, the update PR should be automatically merged.

**Acceptance Criteria**
GIVEN any implementation CNB in a language family CNB(Node.js) is updated
THEN I see that there is a PR to the language family CNB with the implementation CNB updates
AND when the pipelines pass
THEN I see that the PR has been auto-merged

**Notes**
Here is a concourse task that is used bump cnb dependencies:
https://github.com/cloudfoundry/buildpacks-ci/tree/ce29842908d77018051422560db38df9fdbfa33c/tasks/cnb/update-cnb-dependency

**Comment by ryanmoran** [comment]
Tasks:
- [ ] Workflow that sends repository dispatch webhook the the nodejs repo
- [ ] Workflow that responds to repository dispatch event and updates buildpack.toml with PR
- [ ] If the PR checks pass, auto-merge the PR

**Comment by kvedurmu** [comment]
Looks great! The latest release of the Node.js Paketo Buildpack (https://github.com/paketo-buildpacks/nodejs/releases/tag/v0.0.2) has the latest versions of the Node.js implementation buildpacks. Closing this.
