### ISSUE TITLE
Create a Tini Buildpack that provides the Tini Process Manager as a Dependency

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/nodejs#179]
In order to implement the [Node.js architecture RFC](https://github.com/paketo-buildpacks/nodejs/blob/master/rfcs/0001-buildpacks-architecture.md) could we create a Buildpack that provides Tini process manager as a dependency?

**Comment by arjun024** [comment]
See https://github.com/paketo-buildpacks/tini/pull/1
