### ISSUE TITLE
Self-nomination as NodeJS contributor

### ISSUE THREAD

**Issue by floragj** [paketo-buildpacks/nodejs#232]
In keeping with [the Paketo Buildpacks Governance document](https://github.com/paketo-buildpacks/community/blob/main/GOVERNANCE.md), I am self-nominating as a contributor to the NodeJS language family.

My PRs implementing the [node-start buildpack](https://github.com/paketo-buildpacks/node-start/pull/3) and adding offline tests to the [tini buildpack](https://github.com/paketo-buildpacks/tini/pull/3) have both been accepted.

**Comment by arjun024** [comment]
**Vote Yes**. Thank you for the important contributions you have made. I'll be glad to see you join the Contributor team.

**Comment by thitch97** [comment]
I also **vote yes** to you being a contributor!

**Comment by arjun024** [comment]
With a supermajority vote of a maintainers, nomination accepted
