### ISSUE TITLE
Support HTTP requests using system CA bundle

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/nodejs#253]
Similar to https://github.com/paketo-community/python/issues/178, we should look it easier to make HTTP requests within Node apps when a system/operator defined CA certificate is present. We can do this by setting `NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt` (see https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file)

**Comment by arjun024** [comment]
@kvedurmu Can this be closed due to https://github.com/paketo-buildpacks/nodejs/issues/308?

**Comment by kvedurmu** [comment]
I think that this is additive to #308. I don't have much context into how CA certs work within Node.js so I'd defer to your judgement @arjun024. 

The specific issue in Python was that the environment variable needs to be set if an app has a CA certificate and is using standard http lib to make HTTP requests. So, if users can build an app that's using a CA certificates, and successfully make HTTP requests without setting this environment variable, you're probably right that this can be closed out.

**Comment by fg-j** [comment]
@arjun024 or  @Superv0n, do you have any more context on whether this is still relevant?

**Comment by c0d1ngm0nk3y** [comment]
> The Paketo Buildpack for CA Certificates is a Cloud Native Buildpack that adds CA certificates to the system truststore at build and runtime.

That should cover the described use case.
