### ISSUE TITLE
Are there CNCF build packs?

### ISSUE THREAD

**Issue by mhdawson** [paketo-buildpacks/nodejs#263]
On https://paketo.io/ it seems to refer to https://buildpacks.io/. 

I looked at the content of the repo and was expecting to see a `bin` directory with `detect` and `build` scripts as described in https://buildpacks.io/docs/buildpack-author-guide/create-buildpack/building-blocks-cnb/#detect-and-build but I can't find them. 

I'm I looking in the wrong place or is there something else I'm misunderstanding?

**Comment by floragj** [comment]
Hey there! Paketo buildpacks do indeed comply with the CNCF spec. This buildpack (nodejs) is what we call a *language-family buildpack*, which basically combines a bunch of implementation buildpacks into a more easy-to-use artifact.

Buildpacks like https://github.com/paketo-buildpacks/node-engine are *implementation buildpacks*, meaning that they actually implement the CNB spec. When we build the implementation buildpacks from the source code checked into the repo linked above, they end up having runnable `build` and `detect` binaries.

You can find list of the implementation buildpacks inside the nodejs language family here in the language family [README](https://github.com/paketo-buildpacks/nodejs/blob/main/README.md).

Hope that helps!

**Comment by arjun024** [comment]
Buildpacks.io link: https://buildpacks.io/docs/concepts/components/buildpack/#meta-buildpack

**Comment by mhdawson** [comment]
@fg-j thanks for the clarification.  If the buildpacks once created have build and detect binaries then that makes sense. Will have to look at those instead of the source.
