### ISSUE TITLE
Allow users to use a specific version of npm

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/nodejs#270]
The current set of buildpacks installs a version of `npm` based on the chosen version of `node`. Sometimes users will want to choose a different version of `npm` than the version that came with the `node` version they've chosen. We should create a mechanism for users to specify a version of `npm` to install.

**Comment by fg-j** [comment]
@ryanmoran or @trevorblades, is this still a relevant feature request for you?

**Comment by ryanmoran** [comment]
Yes. I would like to see this happen.

**Comment by fg-j** [comment]
@paketo-buildpacks/nodejs-maintainers Any blockers or things to keep in mind when implementing this feature?

**Comment by c0d1ngm0nk3y** [comment]
@ryanmoran What would be the reason for choosing a different version of `npm`? A more current one?

**Comment by ryanmoran** [comment]
@c0d1ngm0nk3y yes. Or to be able to roll back to a different version if a bug is discovered in the version that ships with Node.js.

**Comment by Waterstraal** [comment]
Is this feature still under consideration? There are reasons to use a different npm version than the default one, such as bugs or testing new features

**Comment by c0d1ngm0nk3y** [comment]
What about if the `npm-install` buildpack receives a `BP_NPM_VERSION` which results in `npm install npm@<version>` being installing the actual `node-modules`?
