### ISSUE TITLE
Allow users to specify the Node.js source path

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/nodejs#272]
It would be helpful to have an environment variable that users can set to specify the base path of their Node.js source code. This would be similar to the `BP_GO_TARGETS` environment variable that's supported in the Go Buildpack.

Having separate environment variables per language family would be useful for building polyglot apps such as a Go backend and Node.js frontend that might have a structure similar to the following:
```
src
  -> frontend
      -> package.json
      -> my frontend code
  -> go.mod
  -> main.go   
```

**Comment by ForestEckhardt** [comment]
Just to clarify, you want to be able to specify a root that is not the WorkingDir, you aren't looking to be able to pass a list of dirs to be built?

**Comment by kvedurmu** [comment]
> Just to clarify, you want to be able to specify a root that is not the WorkingDir

Right. Exactly this. So if I had the following filesystem structure:
```
workspace -> 
   src
      -> frontend
          -> package.json
          -> my frontend code
      -> go.mod
      -> main.go  
```
and my app is in the `src` directory, I'd want to be able to build my app like:
```
pack build polyglot-app --path ./workspace/ --env BP_INCLUDE_FILES="frontend/" --env BP_NODEJS_ROOT="frontend/" --buildpack gcr.io/paketo-buildpacks/node-engine --buildpack gcr.io/paketo-buildpacks/npm-install --buildpack gcr.io/paketo-buildpacks/go-dist --buildpack gcr.io/paketo-buildpacks/go-mod-vendor --buildpack gcr.io/paketo-buildpacks/go-build
```

**Comment by kvedurmu** [comment]
@arjun024 sounds like this will get closed out by implementation of https://github.com/paketo-buildpacks/nodejs/issues/305, right?

**Comment by arjun024** [comment]
@kvedurmu Doing a little clean up of issues. This problem should be solved by https://github.com/paketo-buildpacks/nodejs/issues/327
