### ISSUE TITLE
Node.js Language family CNB releases should contain a buildpackage artifact

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/nodejs#3]
**Context**
As buildpackages start to become the standard of shipping our CNBs, we should build a buildpackage of our Paketo language family Node.js CNB. This will make it way easier for users to consume specific language family buildpacks.

**Proposal**
start publishing a Paketo Node.js buildpackage whenever we ship a new release artifact. 

**Notes/Helpful Links**
- The pack command that we will have to run to do this is `pack package-buildpack <NAME-OF-ARTIFACT> --package-config <Path/To/Package.toml>`. 
- An example buildpackage.toml file for the OSS NodeJS CNB. Each `uri` should be the path to a packaged up meta/implementation CNB.

```
[buildpack]
uri = "/path/to/nodejs-cnb/nodejs-cnb_package"

[[dependencies]]
uri = "/path/to/npm-cnb/npm-cnb_package"

[[dependencies]]
uri = "/path/to/yarn-cnb/yarn-cnb_package"

[[dependencies]]
uri = "path/to/node-engine-cnb/node-engine-cnb_package"
```

**Acceptance/Deliverables**
- Node.js Language Family CNB github releases should contain an online buildpackage artifact in the release assets.
- Node.js Buildpackage can be downloaded from Github and used to `pack build` apps

**Comment by dwillist** [comment]
Tasks: 
- [ ] Factor out tag bumping into separate github action.
- [ ]  Finds most recent release.
  - [ ] if it is a draft delete.
  - [ ] if not continue.
- [ ] Create a buildpackage artifact.
- [ ] Create a release & fill out body.
- [ ] Upload buildpackage artifact to release.

**Comment by kvedurmu** [comment]
Looks great! I was able to download the buildpackage artifact from the latest release and `pack build` an app using it. Closing this.
