### ISSUE TITLE
Add Azure Applications Buildpack to group ordering

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/nodejs#311]
We should add the [Azure Application Insights buildpack](https://github.com/paketo-buildpacks/azure-application-insights) to each group in the Node.js buildpack so that developers can configure their apps to use the Azure application insights agent.

**Comment by fg-j** [comment]
@paketo-buildpacks/nodejs-maintainers or @Superv0n  Do we have any users requesting this feature? If not, perhaps it's time to close this and allow folks to reopen it if/when they want this feature.

**Comment by mhdawson** [comment]
Going to close based on the last comment and the age of the issue.
