### ISSUE TITLE
Upgrade this buildpack to Buildpack API 5

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/nodejs#326]
## What happened?

* What were you attempting to do?

I wanted to see that Paketo buildpacks are up to date with the latest CNB Spec for buildpacks.

* What did you expect to happen?
I expected to see that in the buildpack.toml for the buildpack, its API version was `0.5` since that's the latest release of the spec.

* What was the actual behavior? Please provide log output, if possible.
The actual API version is `0.2` on the main branch of this repo (and in the latest release).

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.

* What buildpacks are you using? Please include versions.

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

## Checklist

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [ ] I have included steps for reproduction.

**Comment by arjun024** [comment]
If there are any features missing in the buildpack that could be done with updating the buildpack api version, we should look at doing it. Until there's such a request, we should probably defer this work.

**Comment by fg-j** [comment]
Closing, since this buildpack is now on [API v0.6](https://github.com/paketo-buildpacks/nodejs/blob/c9d494bf6cd0025379a6c1d1883f3a9cce530223/buildpack.toml#L1)
