### ISSUE TITLE
Implement support for BP_NODE_PROJECT_PATH as described in RFC 0003

### ISSUE THREAD

**Issue by arjun024** [paketo-buildpacks/nodejs#327]
Requesting implementation of build-time variable`$BP_NODE_PROJECT_PATH` as described in [RFC 0003](https://github.com/paketo-buildpacks/nodejs/blob/main/rfcs/0003-buildpack-yml-to-env-var.md)

Given an app structured as below:
```
. -> 
   src
      -> nodefiles
          -> package.json
          -> my frontend code
      -> go.mod
      -> main.go  
   dist
      -> hello.js
 ```
users should be able to use build-time env variable values `BP_NODE_PROJECT_PATH=./src/nodefiles` or `BP_NODE_PROJECT_PATH=src/nodefiles` to set the path that will be considered as the root of the app by nodejs buildpacks.

This will involve changes to all [nodejs buildpacks](https://github.com/paketo-buildpacks/nodejs#gcriopaketo-buildpacksnodejs) except the yarn buildpack. See [issue](https://github.com/paketo-buildpacks/nodejs/issues/272) for a user request.

**Comment by ForestEckhardt** [comment]
Places where project path needs to modify the WorkingDir:
* For Node Engine:
  * [ ] Use project path in `detect` when searching for `.nvmrc` and `.node-version`
* For Yarn Install:
  * [ ] Use project path in `detect` when searching for `yarn.lock` and `package.json`
  * [ ] Use project path in `build` when running the install, node_modules removal, and node_modules symlink processes
* For NPM Install:
  * [ ]  Use project path in `detect` when searching for `package.json`
  *  [ ] Use project path in `build` when running the install, node_modules removal, and node_modules symlink processes
* For Yarn Start:
  * [ ] Use project path in `detect` when searching for `yarn.lock`
  * [ ] Use project path in `build` when writing the start command to have it execute in the correct directory 
* For NPM Start:
  * [ ] Use project path in `detect` when searching for `package.json`
  * [ ] Use project path in `build` when writing the start command to have it execute in the correct directory
* For Node Start:
  * [ ] Use project path in `detect` when searching for a viable application
  * [ ] Use project path in `build` when writing the start command to have it execute in the correct directory

**Comment by arjun024** [comment]
Support for `BP_NODE_PROJECT_PATH` available in https://github.com/paketo-buildpacks/nodejs/releases/tag/v0.2.0
