### ISSUE TITLE
Nominate Emily Johnson (@emmjohnson) as Nodejs Contributor

### ISSUE THREAD

**Issue by arjun024** [paketo-buildpacks/nodejs#344]
In accordance with the [Paketo Buildpacks Governance document](https://github.com/paketo-buildpacks/community/blob/main/GOVERNANCE.md), I am nominating Emily Johnson (@emmjohnson) as a contributor to the Nodejs language family. Emily is a regular contributor to the buildpack family (https://github.com/paketo-buildpacks/nodejs/pull/321, https://github.com/paketo-buildpacks/node-engine/pull/240 etc.).

**Comment by thitch97** [comment]
+1

**Comment by arjun024** [comment]
With supermajority vote of maintainers in the affirmative, the nomination is considered to be approved.
Welcome to the team of Nodejs Contributors @emmjohnson!

@paketo-buildpacks/steering-committee  Could you please add Emily to the contributors team on github?

**Comment by ryanmoran** [comment]
@emmjohnson Congrats!

@arjun024 Done!
