### ISSUE TITLE
Remove buildpack.yml support

### ISSUE THREAD

**Issue by arjun024** [paketo-buildpacks/nodejs#379]
### Context

With the upcoming [removal of Node 10.x line](https://github.com/paketo-buildpacks/node-engine/pull/281) from the buildpack, the maintainers will be releasing a major version (v1.0.0) of the [node-engine buildpack](https://github.com/paketo-buildpacks/node-engine) as well as this nodejs family buildpack. 

As [notified here](https://github.com/paketo-buildpacks/node-engine/tree/v0.3.1#specifying-a-node-version), this also means that all support for buildpack.yml configurations will be removed

### Proposal

* Remove support for buildpack.yml support configurations like node version, optimize-memory switch.
* Remove/Change all documentation in all READMEs and Paketo docs to reflect that buildpack.yml configurations are not supported.

**Comment by fg-j** [comment]
@arjun024 – any update on when v1.0.0 of this buildpack is planned to be released?

**Comment by ryanmoran** [comment]
I'd be happy to see us move to a v1 once we land the outstanding SBoM work.

**Comment by fg-j** [comment]
@ryanmoran Makes sense. I created #496 to track SBOM work and added it to the v1.0.0 milestone.
