### ISSUE TITLE
Cannot override the version of node-engine

### ISSUE THREAD

**Issue by juergenzimmermann** [paketo-buildpacks/nodejs#423]
## What happened?

* What were you attempting to do?
When I use a `project.toml` as shown below, then `node-engine:0.5.0` is used, but not the configured `node-engine:0.6.0`.

* What did you expect to happen?
I expected that the version of node-engine can be overridden.

* What was the actual behavior? Please provide log output, if possible.
```
pack build juergenzimmermann/buch:1.0.0 --builder paketobuildpacks/builder:base
...
===> DETECTING
5 of 8 buildpacks participating
paketo-buildpacks/ca-certificates 2.3.2
paketo-buildpacks/node-engine     0.5.0
paketo-buildpacks/npm-install     0.4.0
paketo-buildpacks/npm-start       0.3.0
paketo-buildpacks/procfile        4.2.2
...
```

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you using? Please include a version.
pack 0.20.0+git-66a4f32.build-2668

* What buildpacks are you using? Please include versions.
See above

* What builder are you using? If custom, can you provide the output from `pack inspect-builder <builder>`?
paketobuildpacks/builder:base

* Can you provide a sample app or relevant configuration (`buildpack.yml`, `nginx.conf`, etc.)?
`project.toml` for pack 0.20:

```
[project]
id = "com.acme.buch"
name = "Microservice buch"
version = "1.0.0"
authors = ["Juergen.Zimmermann@h-ka.de"]

[[project.licenses]]
type = "GPL-3.0"

[build]
# fuer Verzeichnis /workspace im Image
include = [
  "/dist/src",
  "/.npmrc",
  "/.slugignore",
  "/Procfile",
  "/package*.json",
  "/project.toml",
]

[[build.buildpacks]]
uri = "gcr.io/paketo-buildpacks/nodejs:0.6.0"

[[build.buildpacks]]
uri = "gcr.io/paketo-buildpacks/node-engine:0.6.0"

[[build.env]]
name = "BP_NODE_VERSION"
value = "16.4.2"

[[build.env]]
name = "BP_LAUNCHPOINT"
value = "./dist/src/main.js"

[[build.env]]
name = "NODE_VERBOSE"
value = "true"

[[build.env]]
name = "NPM_CONFIG_LOGLEVEL"
value = "verbose"
```

**Comment by ryanmoran** [comment]
Dependencies flow backwards, so you need to put `node-engine` before `nodejs`. The way the resolver works is that each buildpack can provide or require a set of dependencies. If you put the newer `node-engine` at the end of the list, there are no subsequent buildpacks to require the dependency it provides. Instead, include it at the front and it should override the dependency provided by the older `node-engine` buildpack and be chosen for the build.

**Comment by juergenzimmermann** [comment]
@ryanmoran Thank you! Defining the dependant `node-engine` before `nodejs` works as expected. I close the issue.
