### ISSUE TITLE
Unable to run a nodejs project as yarn is not present in path

### ISSUE THREAD

**Issue by anoop2811** [paketo-buildpacks/nodejs#456]
## What happened?
I have an application which requires yarn to start at run time but yarn is not present in the path in the run image.

* What were you attempting to do?
Run application called backstage (backstage.io)

* What did you expect to happen?
Expected it to run using the yarn start

* What was the actual behavior? Please provide log output, if possible.
`bash: yarn: command not found`
## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.
`pack build backstage-buildpack --path . --builder paketobuildpacks/builder:full`

* What buildpacks are you using? Please include versions.
Was using the packeto nodejs buildpack

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?
paketobuildpacks/builder:full

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?
[package copy.json.txt](https://github.com/paketo-buildpacks/nodejs/files/7205211/package.copy.json.txt)

## Checklist

* [x ] I have included log output.
* [x ] The log output includes an error message.
* [x ] I have included steps for reproduction.

**Comment by arjun024** [comment]
Hi @anoop2811, thanks for the report. I have a couple of questions for you.

(1) Do you have a `yarn.lock` at the root of your application? This is how the nodejs composite buildpack determines if package manager to use is `yarn` or `npm`. `npm` is the default package manager for all node.js applications unless a `yarn.lock` is present at the root. See sample app https://github.com/paketo-buildpacks/samples/tree/main/nodejs/yarn

(2) Are you expecting to use yarn2? If yes, paketo does not have yarn2 support yet. Please see the discussion here (https://github.com/paketo-buildpacks/yarn/issues/19)

**Comment by anoop2811** [comment]
Hi @arjun024 , yes, I do have a yarn.lock file at the root of the application and I am not using yarn2.

**Comment by arjun024** [comment]
Could you provide the build logs and a sample app if possible?

**Comment by anoop2811** [comment]
Hi @arjun024,
  Please find the sample project here: https://github.com/anoop2811/backstage
  Build logs attached:
[build.log.txt](https://github.com/paketo-buildpacks/nodejs/files/7206679/build.log.txt)
Run error: ```docker run -p 3000:3000 -it  backstage-buildpack
bash: yarn: command not found```

**Comment by arjun024** [comment]
Thanks for the sample and logs. As of now, the yarn-start buildpack only makes `yarn` available to the build stage and not in the final built application image. I think it's reasonable for the nodejs buildpack to support a case where the start command is of the syntax `yarn workspace <workspace_name> <command>`. I'll work on a change to get `yarn` available at launch and try to get it released soon.

In the meantime, you can make use of the [`build-plan` buildpack](https://github.com/paketo-community/build-plan). You need a `plan.toml` at the root of the application asking `yarn` to be available at `launch` time i.e. the final application image. See e.g. [here](https://github.com/paketo-buildpacks/yarn/blob/v0.4.1/integration/testdata/default_app/plan.toml)

**Comment by anoop2811** [comment]
Thanks @arjun024 .
 I tried addind the following plan.toml
[plan.toml.txt](https://github.com/paketo-buildpacks/nodejs/files/7212355/plan.toml.txt)
and tried again using the following command:
`pack  build backstage-buildpack --path . --builder paketobuildpacks/builder:full -b paketo-buildpacks/nodejs@0.8.0 -b paketo-community/build-plan@0.0.12`

but I still get the same error

**Comment by arjun024** [comment]
@anoop2811 With v0.9.0 of the nodejs buildpack, you should be able to have `yarn` available on the application image. See [example app](https://github.com/paketo-buildpacks/yarn-start/tree/v0.3.0/integration/testdata/workspaces_app). Feel free to reopen the issue if the problem persists.
