### ISSUE TITLE
Trouble with npm start application with builder 0.1.202-base and newer

### ISSUE THREAD

**Issue by matejvasek** [paketo-buildpacks/nodejs#492]
## What happened?
I am building node application.
Up until recently it worked just fine, but with newer builder 0.1.202-base and newer there is an issue.
Build seems to pass but resulting image is crashing:
```
bash: faas-js-runtime: command not found 
```
`faas-js-runtime` is a node module.

```json
  "scripts": {
    "test": "node test/unit.js && node test/integration.js",
    "start": "faas-js-runtime ./index.js",
    "debug": "nodemon --inspect ./node_modules/faas-js-runtime/bin/cli.js ./index.js"
  },
```

Few observations:
* If node version is fixed to `14` in `package.json` then the resulting image works.
However the application being build works just fine with node `16` locally.
* If I remove `package-lock.json` the resulting image works too.
* If I run locally `npm install`  (which creates `node_modules`) then the build fails.
  ```
  [builder] ERROR: failed to build: exit status 1
  ERROR: failed to build: executing lifecycle. This may be the result of using an untrusted builder: failed with status code: 51
  ```

## Build Configuration

* I am using `pack`.

* What buildpacks are you using? Please include versions.
```
===> DETECTING
[detector] 5 of 10 buildpacks participating
[detector] paketo-buildpacks/ca-certificates 2.4.2
[detector] paketo-buildpacks/node-engine     0.11.0
[detector] paketo-buildpacks/npm-install     0.6.0
[detector] paketo-buildpacks/node-module-bom 0.2.0
[detector] paketo-buildpacks/npm-start       0.6.0
```

* I am using base builder.

## Checklist

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [ ] I have included steps for reproduction.

**Comment by matejvasek** [comment]
Code I am trying to build:
https://github.com/knative-sandbox/kn-plugin-func/tree/main/templates/node/http
```
pack build my-fn --builder gcr.io/paketo-buildpacks/builder:0.1.202-base
```

**Comment by matejvasek** [comment]
I tried to build also: https://github.com/delvedor/fastify-example with similar result:
```
bash: fastify: command not found
```

**Comment by lance** [comment]
This illustrates the problem during the build phase and not at the run phase. But I think the root cause is the same - that is that the `node_modules` folder is not in the expected location for an command run from a package.json to work.

Place this file in an empty directory and run `npm run build`, and you'll see a similar failure.

```json
{
  "name": "paketo-test",
  "main": "index.js",
  "scripts": {
    "build": "pack build paketo-test --builder gcr.io/paketo-buildpacks/builder:base",
    "start": "hello-world-npx",
    "image": "docker run --rm -it paketo-test"
  },
  "license": "ISC",
  "dependencies": {
    "hello-world-npx": "^0.3.0",
    "pino": "^7.3.0"
  }
}
```

**Comment by arjun024** [comment]
I think I have some idea why this is happening. The npm-install buildpack adds `/layers/paketo-buildpacks_npm-install/modules/node_modules/.bin` to the PATH. Node/npm newer versions were refusing to follow a symlinked `node_modules` and they were to assumed to be taken care here ([link](https://github.com/paketo-buildpacks/npm-install/blob/v0.6.0/install_build_process.go#L59-L77)) but it doesn't look this fixed it.

The `nodejs/angular-npm` app in this PR branch https://github.com/paketo-buildpacks/samples/pull/176 can be used to validate the error. It succeeds build, but fails run with `ng: command not found`.
In the built app, `/workspace/node_modules` is a directory not a symlink.
```
cnb@98e45a5973c6:/$ ls -al /workspace/ | grep node_modules
drwxr-sr-x 612 cnb  cnb   20480 Jan  1  1980 node_modules
```
@thitch97 @ryanmoran @sophiewigmore
