### ISSUE TITLE
Can not run node inside the container 

### ISSUE THREAD

**Issue by 2bezzat** [paketo-buildpacks/nodejs#522]
## What happened?
I want to access the running docker container and run some scripts inside it, for example running the migrations of the app inside, so I logged into the container `docker exec -it container_name /bin/sh` and tried to execute that command `node -v` and got this output: 
`/bin/sh: 52: node: not found` 

btw, I can run python and ruby but can not run node or npm commands, and I'm not using either python or ruby in my codebase 

* I wanted to go inside the created container and run `node -v` 
* I expected that the command would run, assuming we already have nodejs running and will print the nodejs version using the container 

* the output was `/bin/sh: 2: node: not found`

## Build Configuration

*I'm using pack platform

* What buildpacks are you using? Please include versions.

* paketobuildpacks/builder:full

## Checklist

* [] I have included log output.
* [ ] The log output includes an error message.
* [ ] I have included steps for reproduction.

**Comment by ryanmoran** [comment]
You'll need to invoke the lifecycle launcher which will then run your command with the correct environment.

Try the following:
```
docker exec -it container_name launcher bash
```
