### ISSUE TITLE
Yarn Workspaces support

### ISSUE THREAD

**Issue by alexopenkowski-the-nu-company** [paketo-buildpacks/nodejs#544]
Is there Yarn Workspaces support? If not, I would be happy to provide a minimal sample application I'd like to build.

**Comment by ryanmoran** [comment]
Yes. Workspaces should be supported. Here is an example: https://github.com/paketo-buildpacks/yarn-install/tree/main/integration/testdata/with_yarn_workspaces. Let us know if you can't get this working the way you would expect.
