### ISSUE TITLE
Error Detect Lifecycle with Base builder version v0.2.26

### ISSUE THREAD

**Issue by srisek** [paketo-buildpacks/nodejs#566]
## What happened?
When using the version v.0.26 and above, the below error is getting reported in the Detect lifecycle phase when trying to build using the base builder.

Error: 

======== Output: paketo-buildpacks/poetry@0.1.2 ========

pyproject.toml must include [tool.poetry.dependencies.python], see https://python-poetry.org/docs/pyproject/#dependencies-and-dev-dependencies

err:  paketo-buildpacks/poetry@0.1.2 (1)

======== Output: paketo-buildpacks/poetry@0.1.2 ========

pyproject.toml must include [tool.poetry.dependencies.python], see https://python-poetry.org/docs/pyproject/#dependencies-and-dev-dependencies

err:  paketo-buildpacks/poetry@0.1.2 (1)

ERROR: No buildpack groups passed detection.

ERROR: failed to detect: buildpack(s) failed with err

*This works fine when using the base builder version v0.2.25.

Below is the output when trying to use base builder version v0.2.25 in detect lifecycle phase

======== Output: paketo-buildpacks/poetry@0.1.2 ========
pyproject.toml must include [tool.poetry.dependencies.python], see https://python-poetry.org/docs/pyproject/#dependencies-and-dev-dependencies
err:  paketo-buildpacks/poetry@0.1.2 (1)
======== Output: paketo-buildpacks/poetry@0.1.2 ========
pyproject.toml must include [tool.poetry.dependencies.python], see https://python-poetry.org/docs/pyproject/#dependencies-and-dev-dependencies
err:  paketo-buildpacks/poetry@0.1.2 (1)
6 of 10 buildpacks participating
paketo-buildpacks/ca-certificates 3.1.0
paketo-buildpacks/node-engine     0.12.2
paketo-buildpacks/npm-install     0.8.0
paketo-buildpacks/node-module-bom 0.2.3
paketo-buildpacks/node-run-script 0.3.2
paketo-buildpacks/npm-start       0.8.0

* What were you attempting to do?

Trying to build Node js angular application in the first phase using node js buildpack  and using Nginx build pack to create the final build in Tekton using lifecycle phases.

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.

Tekton - v0.33.2 ( tekton-pipelines)

CNB Platform API version - 0.8

* What buildpacks are you using? Please include versions.

Nodejs
Nginx

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?

base builder

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

project Structure

├── README.md
├── angular.json
├── cypress
├── cypress.json
├── karma.conf.js
├── local
├── mime.types
├── nginx-conf.template
├── node_modules
├── pa11yci
├── package-lock.json
├── package.json
├── proxy.conf.json
├── proxyssl.conf.json
├── sonar-project.properties
├── src
├── tsconfig.app.json
├── tsconfig.json
└── tsconfig.spec.json

The buildpacks uses the nodejs buildpacks to build the node app and then tekton step has a logic to re-name the nginx-conf.template to nginx.conf and then run the nginx buildpacks to create the final image.

**Comment by ryanmoran** [comment]
This should be resolved by https://github.com/paketo-buildpacks/nodejs/releases/tag/v0.17.1.

That release is now available in the following builders:
* https://github.com/paketo-buildpacks/full-builder/releases/tag/v0.2.38
* https://github.com/paketo-buildpacks/base-builder/releases/tag/v0.2.30

Please let us know if you are still experiencing issues.
