### ISSUE TITLE
BP_NODE_PROJECT_PATH environment variable doesn't work for npm workspaces

### ISSUE THREAD

**Issue by pmbanugo** [paketo-buildpacks/nodejs#586]
## What happened?

* What were you attempting to do?
I want to build and run an app in an npm workspace. I ran `pack build store-product --builder paketobuildpacks/builder:base --env BP_NODE_PROJECT_PATH=./app/product` which builds as usual. But then when I run the container, it fails because the packages defined within `./app/product/package.json` are not used in the build. It complains of missing dependencies.  A build within the ./app/product directory works as usual. 

* What did you expect to happen?
The app should be built successfully and the packages installed accordingly.

* What was the actual behaviour? Please provide log output, if possible.
The dependencies defined in package.json for the app are not installed. It seems to use the package.json of the root npm workspace.

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.
pack CLI

* What buildpacks are you using? Please include versions.

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?
 paketobuildpacks/builder:base

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

A typical npm workspace with a root package.json and individual apps defined in a `app` directory.

## Checklist

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [ ] I have included steps for reproduction.

**Comment by ryanmoran** [comment]
I can't seem to replicate this. I've got an app with the following structure:

```
├── README.md
├── package.json
└── server
    ├── package.json
    └── server.js
```

Then I run the following command:
```
pack build workspace-app --builder paketobuildpacks/builder:base --env BP_NODE_PROJECT_PATH=./server
```

When I then run the container, it works successfully:
```
$ docker run -it -p 8080:8080 workspace-app
server is listening on 8080
```

Can you provide us with some more details on the structure of your application? Or maybe even a link to an app that reproduces the issue?

**Comment by pmbanugo** [comment]
I'm closing this because I switched to yarn and this works
