### ISSUE TITLE
Support Jammy Jellyfish

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/nodejs#607]
## Describe the Enhancement

Ultimately, we want to be able to build Nodejs apps on top of the Paketo Jammy stacks. Currently, builds fail because buildpacks like `node-engine` don't have the Jammy stack listed in their supported stacks.

## Possible Solution

- Update `buildpack.toml` and dependencies to add `io.buildpacks.stacks.jammy` as a compatible stack
- https://github.com/paketo-buildpacks/node-engine/issues/487
- (If necessary) Recompile installed dependencies to work on Jammy 
- Add some integration tests that test the buildpack against Jammy

## Motivation

Part of https://github.com/paketo-buildpacks/builder-jammy-base/issues/1

**Comment by sophiewigmore** [comment]
TODO - all should only need a testing strategy but already work on `*` stack:
NPM Install 
Yarn Install 
Node Run Script
Node Start
NPM Start
Yarn Start

**Comment by sophiewigmore** [comment]
All buildpacks up to date, released and included in https://github.com/paketo-buildpacks/nodejs/releases/tag/v0.22.0

**Comment by sophiewigmore** [comment]
Released in Jammy builders:
https://github.com/paketo-buildpacks/builder-jammy-full/releases/tag/v0.1.0
https://github.com/paketo-buildpacks/builder-jammy-base/releases/tag/v0.1.0
