### ISSUE TITLE
Implement RFC0052: Graceful Stack Upgrades

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/nodejs#636]
[RFC](https://github.com/paketo-buildpacks/rfcs/blob/main/text/0052-graceful-stack-upgrades.md)

## Summary

All Paketo Buildpacks should support graceful stack upgrades between the current Bionic and Jammy stacks. For most buildpacks, this should not require any changes, but for some buildpacks, layers created in previous builds that would normally be reused should be recreated if the stack ID changes.

## Action Item
Consider what types of buildpacks would be impacted by a stack upgrade and make any relevant changes that would help to mitigate issues caused by that upgrade. If there is no work to be done, please comment on this issue explaining the context that helped to arrive at that conclusion.

**Comment by thitch97** [comment]
After some investigation, it would appear to me that, at least for now, we can afford not to make any changes to any of the implementation buildpacks in support of upgrading stacks smoothly between builds. In testing, the main concerns were:

1. `npm-install` & `yarn-install`: Whether preserving cached `node_modules` layers would cause failures.
    
    I have not observed any failures after adding arbitrary packages to npm & yarn applications
    
2. `npm-install`: Whether reusing the `npm-cache` between builds would cause failures (there is no yarn equivalent cache to worry about in `yarn-install`)
    
    The buildpack’s current behaviour refreshes the `npm-cache` on each invocation of `npm install` or `npm ci`. There does appear to be some faulty logic in the buildpack when users provide their own `npm-cache`, but that is outside the scope of this issue.
    
3. What effect, if any, changing the stack would have on native extensions
    
    I’ve built a number of apps from [this repo](https://github.com/nodejs/node-addon-examples) and have seen no failures when upgrading stacks between builds. To ensure the validity of these test apps, I tried building them with the `base` stack with the expectation that they would fail to build due to the lack of C/C++ native extension support. Observing that the `base` builds did fail, that building the same apps on `full` succeeded and that there were no failures switching between bionic and jammy full stacks I have reasonable confidence that this will not pose any issues.
