### ISSUE TITLE
Remove the Node Module BOM buildpack

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/nodejs#681]
## Describe the Enhancement

We already support output of Node modules using Syft. The output is better than what we get this this other buildpack. We should remove this buildpack prior to cutting a 1.0 release.

## Possible Solution

Remove the buildpack from all groups where it is referenced.

## Motivation

With the 1.0 release, we have the chance to clean up some code that we no longer want to maintain. We should take advantage of this.

**Comment by loewenstein** [comment]
Outch, I would have expected that a Node specific tool works as least as good as a generic tool like `syft`. There is even a [quite similar request](https://github.com/paketo-buildpacks/java/issues/842) to support the Maven plugin for sboms…
