### ISSUE TITLE
Unified log output for all buildpacks used (ideally even between language families)

### ISSUE THREAD

**Issue by c0d1ngm0nk3y** [paketo-buildpacks/nodejs#766]
When using the `nodejs`, you get a different log output compared to `java`. It varies even between buildpacks since the `ca-certificates` buildpack is used in both meta buildpacks.

## Describe the Enhancement

All buildpacks should make use of the nicer log output of `libpak/bard`.

## Possible Solution

How about moving `libpak/bard` to a separate repository to be used in all buildpacks and then bit by bit use this instead until we can remove `libpak/bard` and 'packit/scribe' altogether?

## Motivation

If you try the [npm sample](https://github.com/paketo-buildpacks/samples/tree/main/nodejs/npm), you will get somewhat confusing log output which is caused by the first buildpack to use a different logger.
In addition, if you use `java` and `nodejs`, the log output is not as unified than it could be. That would make a better user experience.

**Comment by loewenstein** [comment]
@c0d1ngm0nk3y I brought this up in the working group meeting and @sophiewigmore's suggestion was to propose this as an RFC (that would likely need a longer period of discussion on convergence).

**Comment by mhdawson** [comment]
@c0d1ngm0nk3y is this still something you plan on pursuing?

**Comment by sophiewigmore** [comment]
Personally I had wanted to propose an RFC and then got really busy with other initiatives and never got to it. I'd love to see someone in the community push this forward if they're so inclined

**Comment by c0d1ngm0nk3y** [comment]
@loewenstein-sap @sophiewigmore 
I opened https://github.com/paketo-buildpacks/rfcs/pull/308, so this can be probably closed.
