### ISSUE TITLE
Optional versioning of buildpacks on go module level. 

### ISSUE THREAD

**Issue by pacostas** [paketo-buildpacks/nodejs#913]
## Describe the Enhancement

Currently, buildpacks support versioning for versions < `2.0.0` as this is the default behavior of golang when no version is specified in the go.mod file https://github.com/paketo-buildpacks/node-engine/blob/a565e1576e32d9c84626ee444a299625b0bc4a50/go.mod#L1 where in that case any version < `2.0.0` will be published on golang registry https://pkg.go.dev/github.com/paketo-buildpacks/node-engine?tab=versions.

Versions > `2.0.0` despite being published as a github releases, do not sync with the golang registry. As a result, there is a misalignment between the version published on github releases such as [4.1.4](https://github.com/paketo-buildpacks/node-engine/releases/tag/v4.1.4) and those on the golang registry such as [1.9.0](https://pkg.go.dev/github.com/paketo-buildpacks/node-engine?tab=versions) . 

Not only is it confusing to have misaligned versions, but it also makes it impossible for third-party go modules to consume the latest state of each buildpack at a golang modle level. Despite being published on github releases, cannot be published on the golang registry due to version > `2.0.0`.

## Possible Solution

The solution is to develop major versions as stated on the golang documentation https://go.dev/doc/modules/major-version by creating a PR similar to this one https://github.com/paketo-buildpacks/node-engine/pull/966 which will add or update the `/vX` keyword in the go.mod file when there is a major version bump on github.

This can be done manually, but it would be preferable to automate it using a github action, to avoid human errors. Specifically, a github action can periodically check if there is a misalignment between the version published on github releases and those on the golang registry. In case of misalgnment, it will create a PR to bump the version of go module to match with the one published on the github releases. Additionally, to avoid enfocing this versioning pattern on all buildpacks, this functionality will be enabled by setting the `enable_versioning` flag to `true` in a `config.json` file located in the root directory of the module.

In terms of versions that will be maintained, only the latest version will be maintained, and no bug fixes will be made to older versions, as the current repository structure does not support this.

## Motivation

Proper consumption of Paketo builpacks go modules from third party modules by avoiding misalignment of the versions between the github releases and those in the golang registry.

**Comment by mhdawson** [comment]
From some chat in slack sounds like it has been done for at least some Java buildpacks, and that currently versioning is manual.

**Comment by mhdawson** [comment]
@c0d1ngm0nk3y I don't want to set any expectation that they will be kept up to date without the automation. Without the automation I'm ok accepting PRs which update the major version, but I don't think the core Node.js maintainers should worry about keeping them up to date.  It would solely be up to those who want the updates to figure out when a PR is needed and make that update. ie we could document that we accept those updates but won't update them without the external PRs.

On the other hand with the automation in place it think its more reasonable to document that the core maintaners work to keep them up to date based on the automation doing most of the work.

**Comment by mhdawson** [comment]
Discussed a bit in the biweekly Node.js meeting today and we agreed to set the expectation that keeping the go level major versioning up to date will be add hock to start.  If/when people notice they are not in sync PRs will be accepted.

**Comment by c0d1ngm0nk3y** [comment]
I think this can be close, right?

**Comment by pacostas** [comment]
I'm leaving it open till we are sure that we have document it somewhere or at least agree that we dont need to document it somewhere.

**Comment by pacostas** [comment]
PR has been merged
